### PR TITLE
fix: Fix jsPlugin rules not being disabled properly when set and then disabled in shared configs

### LINKED ISSUE #277: Improve merge logic for disabling rules that are set with a config object elsewhere
TL;DR an ESLint config like this (albeit it needs to be done via a shared config, as JS will automatically kick out all but the last usage of the same key in an object):

```js
export default [
  {
    rules: {
      "rulename": [
        "error", { optionFoo: "bar" }
      ],
      'rulename': 'off',
    }
  }
];
```

Should migrate to an oxlint config like this:

```json
{
  "rules": {
    "rulename": "off"
  }
}
```

But instead results in 

```json
{
  "rules": {
    "rulename": [
      "error", { "optionFoo": "bar" }
    ],
  }
}
```

We should fix the merging behavior here.

----

For example, I end up with this when running `node ../oxlint-migrate/dist/bin/oxlint-migrate.mjs --type-aware --js-plugins eslint.config.mjs` on the mastodon repo:

```json
"formatjs/enforce-id": [
  "error",
  {
    "idInterpolationPattern": "[sha512:contenthash:base64:10]"
  }
],
```

But `enforce-id` is explicitly disabled in the eslint config. I think this is because of the merging logic when there's an explicit configuration object?

So the ESLint config basically looks like this:

```js
// this is added because of the import of the `formatjs.configs.strict` config in the main config:
"formatjs/enforce-id": [
  "error",
  {
    "idInterpolationPattern": "[sha512:contenthash:base64:10]"
  }
],
// And then in the actual `rules` list in the eslint.config.mjs:
'formatjs/enforce-id': 'off',
```

See the definition for `formatjs.configs.strict` [here](https://github.com/formatjs/formatjs/blob/0cf819d6f5226ea82fd0e7e7b0dfdb7d65b13341/packages/eslint-plugin-formatjs/index.ts#L154-L158). And then the Mastodon eslint config [here](https://github.com/mastodon/mastodon/blob/9addad8ce5e60702f32801b58d0b3d611093a480/eslint.config.mjs).

So we need to ensure that `off` is prioritized over `error` with a config object when merging these.

This happens on both the latest `main` branch of oxlint-migrate and the current 1.32.0 release. Can reproduce `npx @oxlint/migrate@latest --type-aware --js-plugins eslint.config.mjs` by running [on this commit of mastodon](https://github.com/connorshea/mastodon/commit/4916bf541f667ac49356d0563f1f999f10096d7b) in my fork, which has oxlint installed and all that. Will need to run `yarn install` first as well.

### PR DESCRIPTION
**Pull request by connorshea**
Fixes #277.

This reduces the oxlint errors/warnings for Mastodon (when using jsPlugins and type-aware) down considerably. The migration script was generating a slightly incorrect config, and so a few jsPlugin rules ending up enabled when they were not enabled with ESLint. The behavior here is a bit odd, in that the behavior only seems to impact jsPlugin-based configs.

The difference in the behavior for jsPlugins vs not-jsPlugins seems to be due to the `if (allRules.includes(rule)) {` branch, which excludes rules not defined by the native oxlint rule list automatically.

~~This also improves the override de-duplication logic to include merging overrides such that plugins are also considered for merging purposes, and adds tests accordingly, which fixes some further issues that existed for the migrate scripts.~~

As part of the tests for this, I've introduced an "e2e" directory for explicitly testing that a given ESLint config gets converted into an oxlint config with specific attributes. Basically, a more explicit version of the snapshots.

Easiest to review commit-by-commit, probably.

You can see the changes caused by this PR in [the test commit on Mastodon](https://github.com/connorshea/mastodon/commit/517e44f9c4837d87500cc7158c6c3b7c2ebe5fdc) which updates the oxlint config to be generated by this PR.

Done with a good amount of help from GitHub Copilot/the Raptor mini model.

----

Results from running `yarn run oxlint --type-aware --report-unused-disable-directives` on the mastodon codebase.

When migrated with `npx @oxlint/migrate@1.32.0 eslint.config.mjs --type-aware --js-plugins`:

Found 65 warnings and 1896 errors.

When migrated with `node ../oxlint-migrate/dist/bin/oxlint-migrate.mjs --type-aware --js-plugins eslint.config.mjs` (and this PR):

Found 33 warnings and 152 errors.

So the correctness improvement here is pretty good :)

### CODE REVIEW

File: src/plugins_rules.ts [hunk 1]
```diff
@@ -110,6 +110,10 @@ export const transformRuleEntry = (
       }
     } else {
       if (!isActiveValue(normalizedConfig)) {
+        // if rule is disabled, remove it.
+        if (isOffValue(normalizedConfig)) {
+          delete targetConfig.rules[rule];
+        }
```
Comment (connorshea) [inline src/plugins_rules.ts:150]: This is the actual fix, everything else is refactoring.

File: integration_test/__snapshots__/nuxt-auth.spec.ts.snap [hunk 2]
```diff
@@ -1264,10 +1264,6 @@ exports[`nuxt-auth --js-plugins > nuxt-auth--js-plugins 1`] = `
           "allowSingleLine": true,
         },
       ],
-      "@stylistic/comma-dangle": [
-        "error",
-        "always-multiline",
-      ],
```
Comment (connorshea) [inline integration_test/__snapshots__/nuxt-auth.spec.ts.snap:1270]: This is also an intentional fix, the eslint config has this line which means that it _should_ have ultimately been marked as disabled, but was not being disabled: `'style/comma-dangle': 'off',`

File: src/plugins_rules.ts (hunk 1 above)
Comment (Sysix) [reply src/plugins_rules.ts:150]: This will remove the rule for override rules too.

```
[
  { "rules": {"rule-name": "error"}},
  { "files": "*.spec.ts"], "rules": {"rule-name": "off"}}
]
```

Maybe we should add a cleanup function for checking the `oxlint` configuration at the end :)

File: scripts/generator.ts [hunk 3]
```diff
@@ -18,18 +18,22 @@ export class RulesGenerator {
       ({ category }) => category
     );
     let code =
-      '// These rules are automatically generated by scripts/generator.ts\n\n';
+      '// The rules list is automatically generated by `scripts/generator.ts`\n\n';
+
+    code += `export default {\n`;
```
Comment (Sysix) [inline scripts/generator.ts]: Any reason to refactor this? 
I do not like that we now import ALL rules. Before we could import specific categories, see the tests for example

File: src/plugins_rules.ts [hunk 4]
```diff
@@ -253,25 +257,39 @@ export const cleanUpUselessOverridesRules = (config: OxlintConfig): void => {
   }
 };
 
+type Category =
```
Comment (Sysix) [inline src/plugins_rules.ts]: Can be moved to `types.ts` and maybe updated the type info for:
https://github.com/oxc-project/oxlint-migrate/blob/41303f4d97372b660bc52c5224956c9ef7bd960f/src/types.ts#L5

File: scripts/generator.ts (hunk 3 above)
Comment (connorshea) [reply scripts/generator.ts]: Mainly it allows us to avoid the ts-expect-error usages, and I feel it's cleaner than doing an `import * as rules from 'blah'` in most places. But I will remove these changes from this PR for now.

File: src/plugins_rules.ts (hunk 4 above)
Comment (connorshea) [reply src/plugins_rules.ts]: 👍 Updated the code to do this now

File: scripts/generator.ts (hunk 3 above)
Comment (connorshea) [reply scripts/generator.ts]: If we type it properly, `pedanticRules` and so on do actually work apparently, so this is fine without the change to the generated object shape.

File: src/plugins_rules.ts (hunk 1 above)
Comment (connorshea) [reply src/plugins_rules.ts:150]: You're right, I added a snapshot test for that and confirmed that happens. Although, it seems like it happens even if I remove the code I added?

```js
if (isOffValue(normalizedConfig)) {
  delete targetConfig.rules[rule];
}
```

Comment (connorshea) [reply src/plugins_rules.ts:150]: If I cherry-pick `ca9d8e28144ac0a62f57454ddf6f721d378224c0` from this branch onto main, it actually emits the exact same snapshot result on main as well, so this apparently wasn't broken by my change.

Comment (connorshea) [reply src/plugins_rules.ts:150]: 37f4dad6f6895a4c129157a308f799ce4316a943

I think I've fixed the problem now (with help from our pal Copilot), but it does result in the jsPlugins now being present on overrides unnecessarily in many cases. I'll see if I can fix that...

File: integration_test/__snapshots__/nuxt-auth.spec.ts.snap [hunk 5]
```diff
@@ -1105,6 +1105,7 @@ exports[`nuxt-auth --js-plugins > nuxt-auth--js-plugins 1`] = `
         ],
         "rules": {
           "@typescript-eslint/explicit-function-return-type": "off",
+          "antfu/no-top-level-await": "off",
```
Comment (connorshea) [inline integration_test/__snapshots__/nuxt-auth.spec.ts.snap:1108]: This change is correct. These should be set because the base config sets this to error, and it looks like these rules are intentionally set to `off` in the overrides for these specific files.

File: src/plugins_rules.ts (hunk 1 above)
Comment (connorshea) [reply src/plugins_rules.ts:150]: @Sysix 

> Maybe we should add a cleanup function for checking the oxlint configuration at the end :)

How do you mean?

**Comment by connorshea** [comment]
I noticed that we had a logic issue in merging the `override` configs, and fixed that so that the plugins get merged correctly now.

Stats running the migration script on mastodon with before and after 1ffffd5001c9085de099b4d98d804994e4347b8b:

```
Found 65 warnings and 152 errors.
Finished in 5.9s on 488 files with 128 rules using 8 threads.
```

After fix for plugin merge:

```
Found 33 warnings and 152 errors.
Finished in 6.8s on 488 files with 128 rules using 8 threads.
```

File: src/cleanup.ts [hunk 6]
```diff
@@ -279,3 +282,99 @@ function mergeConsecutiveOverridesWithDifferingFiles(config: OxlintConfig) {
...
+        const other = config.overrides![k];
+
+        // Merge rules with last-wins (later overrides take precedence)
+        if (other.rules) {
+          if (!first.rules) first.rules = {};
+          Object.assign(first.rules, other.rules);
+        }
+
+        // Merge plugins as a set
+        if (other.plugins) {
```
Comment (Sysix) [inline src/cleanup.ts]: I am worried this will make problems when using the `--merge` flag.
Can you simplify the PR to only fix the "jsPlugins" problem and move this part into a new PR :)?

File: src/plugins_rules.ts [hunk 7]
```diff
@@ -67,7 +72,12 @@ const normalizeSeverityValue = (
 export const transformRuleEntry = (
   eslintConfig: Linter.Config,
   targetConfig: OxlintConfigOrOverride,
-  options?: Options
+  options: Options = {
```
Comment (Sysix) [inline src/plugins_rules.ts]: please keep it to `options?: Options`

**Review by Sysix — CHANGES_REQUESTED** [review]

File: src/cleanup.ts (hunk 6 above)
Comment (connorshea) [reply src/cleanup.ts]: Fair enough! I've removed that part of the PR and will add it separately in a later PR.

**Review by Sysix — APPROVED** [review]

**Comment by connorshea** [comment]
Thanks!
