### PR TITLE
fix: Fix plugin scope determination logic

### LINKED ISSUE #377: Incorrect migration of js plugin `@eslint-react/eslint-plugin`
If I use [`@eslint-react/eslint-plugin`](https://www.npmjs.com/package/@eslint-react/eslint-plugin) in a project with ESLint, and I want to migrate it as a JS plugin so that missing oxlint rules are still run through ESLint, then after the migration, when I run oxlint, I get the error:

```log
Failed to build configuration from /Users/rakleed/Developer/eslint-react-oxc-migration/.oxlintrc.json.

  × Failed to load JS plugin: @eslint-react/eslint-plugin-web-api
  │   Cannot find module '@eslint-react/eslint-plugin-web-api'
```

See https://github.com/rakleed/eslint-react-oxc-migration for reproduction example.

### PR DESCRIPTION
**Pull request by connorshea**
This change ensures that the plugin rules are migrated with the correct name (`e18e/rule-name`, not `@e18e/rule-name`). It also ensures that the plugin name that is used is correct.

It _should_ migrate as `"jsPlugins": ["@e18e/eslint-plugin"]`, but prior to this PR did not.

From what I understand, the reason it is `e18e/rule-name` despite the scoped plugin name is that it specifies the `meta.name` field [here](https://github.com/e18e/eslint-plugin/blob/34ff3ef3be562b9fb07ac8b0714e4c1fadf5b233/src/main.ts#L29).

The Tanstack integration test is unchanged as it was already correct.

This also fixes using the usage of `@eslint-react` plugin. Fixes #377.

Generated with Claude Code, tested by me and confirmed as fixing the problem fully.

### CODE REVIEW

File: src/jsPlugins.ts [hunk 1]
```diff
@@ -8,17 +8,67 @@ const ignorePlugins = new Set<string>([
...
+ *   - `@scope/sub` -> `@scope/eslint-plugin-sub`
+ *
+ * For non-scoped names, the npm package could follow either convention:
+ *   - `eslint-plugin-{name}` (e.g. `eslint-plugin-mocha`)
+ *   - `@{name}/eslint-plugin` (e.g. `@e18e/eslint-plugin`)
+ *
+ * We try to resolve both candidates against the installed packages and
+ * use the one that is actually present, falling back to the standard
+ * `eslint-plugin-{name}` convention when neither can be resolved.
+ */
```
Comment (connorshea) [inline src/jsPlugins.ts:36]: This comment is entirely Claude's assumption, I'm pretty sure you _could_ (though if you did, you're insane) have a non-scoped plugin like `eslint-plugin-foo` but set `meta.name` to `@foo`. But I have no idea if we care about supporting that edge-case for now.

File: src/jsPlugins.ts [hunk 2]
```diff
@@ -8,17 +8,67 @@ const ignorePlugins = new Set<string>([
   'local', // ToDo: handle local plugin rules
 ]);
 
-const guessEslintPluginName = (pluginName: string): string => {
+const tryResolvePackage = (packageName: string): boolean => {
+  try {
+    import.meta.resolve(packageName);
```
Comment (connorshea) [inline src/jsPlugins.ts:12]: Only concern is whether it can actually resolve this, e.g. if you use `npx @oxlint/migrate` but your project is using yarn or pnpm, will npx be able to resolve the packages?

**Comment by connorshea** [comment]
Mmm, unfortunately we still end up with the rule name not being compatible with the plugin name, and so this:

```
{
  "rules": { 
    "@eslint-react/naming-convention/context-name": "warn",
    "@eslint-react/naming-convention/ref-name": "warn",
    "@eslint-react/naming-convention/use-state": "warn"
  },
  "jsPlugins": [
    "eslint-plugin-react-naming-convention"
  ],
}
```

Results in this:

```
Failed to build configuration from /Users/connorshea/code/eslint-react-oxc-migration/.oxlintrc.json.

  × Plugin '@eslint-react/naming-convention' not found
  │ 
  │ Plugin '@eslint-react/naming-convention' not found
  │ 
  │ Plugin '@eslint-react/naming-convention' not found
```

I guess we need to either support alias resolution, or otherwise resolve the aliases when porting the rules? :s

**Comment by connorshea** [comment]
Alright, I think this correctly handles all three cases:

- `@e18e/eslint-plugin` but with `e18e` meta.name means that the rules should be `e18e/rule-name`.
- `@tanstack/eslint-plugin-query` can be used with rule names like `@tanstack/query/rule-name`.
- `@eslint-react/eslint-plugin` with sub-plugins is handled correctly, migrates such that we rename the rules to use the canonical scopes (`react-dom/no-flush-sync` for the rule, `eslint-plugin-react-dom` for the plugin), as Oxlint doesn't handle the aliasing right now without using the specifier system in the Oxlint config itself.

I guess we could consider setting this up to explicitly use the aliasing system for the last edge case. Then the rules can have names like `@eslint-react/dom/rule-name`? But I'd rather do that in a separate PR if we want to do it, as I have confirmed that this current PR works correctly as-is, and it fixes a user's active problem.

File: src/plugins_rules.ts [hunk 3]
```diff
@@ -212,13 +224,19 @@ export const transformRuleEntry = (
       if (options?.jsPlugins) {
         // If the rule is disabled, avoid enabling the jsPlugin to prevent noise.
         if (isOffValue(normalizedConfig)) {
+          // Use the resolved (potentially renamed) rule name for consistency
+          // with enabled rules that go through enableJsPluginRule.
+          const resolvedRule = resolveJsPluginRuleName(
+            rule,
+            eslintConfig.plugins
```
Comment (Sysix) [inline src/plugins_rules.ts]: Can a rule be activated from a plugin declaration from another ESLint config?
Something like:

```
export default [
  {"plugins": await import("xyz") },
  {"rules": { "xyz/rule-1": "error" } }
]
```

Comment (connorshea) [reply src/plugins_rules.ts]: hmm, I'm not sure if you can do it async like that, but it can be activated from another config

Comment (Sysix) [reply src/plugins_rules.ts]: The async part was only for code demo :). 
Then we should probably collect first all plugins across every ESLint config?

Comment (connorshea) [reply src/plugins_rules.ts]: Hmm, after thinking on it more: I _think_ the plugins value should be fully resolved at this point in our evaluation of the config. So I'm pretty sure this wouldn't be a problem?

**Comment by connorshea** [comment]
I have merged the integration tests for the `@tanstack` and `e18e` plugins into main via a separate PR to make this one easier to understand and review :)

File: src/plugins_rules.ts (hunk 3 above)
Comment (Sysix) [reply src/plugins_rules.ts]: Not 100% sure, somebody needs to test it :') 
The first call will have only `{"plugins": ...}` and the second call will only have the rule `{"rules": {"xyz-rule1": ...}}`.

`resolveJsPluginRuleName` does not access the global resolved plugin cache. Instead, it relies on `eslintConfig.plugins`

File: src/jsPlugins.ts [hunk 4]
```diff
@@ -52,14 +102,91 @@ export const isIgnoredPluginRule = (ruleId: string): boolean => {
...
+export const resolveJsPluginRuleName = (
+  rule: string,
+  plugins?: Record<string, ESLint.Plugin> | null
+): string => {
+  const pluginName = extractPluginId(rule);
+  if (pluginName === undefined) {
+    return rule;
+  }
+
+  const metaName = plugins?.[pluginName]?.meta?.name;
```
Comment (Sysix) [inline src/jsPlugins.ts:166]: here

File: src/plugins_rules.ts (hunk 3 above)
Comment (connorshea) [reply src/plugins_rules.ts]: I've added a snapshot test and confirmed the behavior of ESLint is as you described, now I just need to fix it...

Comment (connorshea) [reply src/plugins_rules.ts]: Fixed :) e044a9d89310cf79473dd58e83155af254941951

Comment (connorshea) [reply src/plugins_rules.ts]: Ah you mentioned "across all plugins". I didn't realize this case would work as well, let me make sure this case is fixed 🙃 
```
import e18e from '@e18e/eslint-plugin';

export default [
  {
    rules: {
      'e18e/prefer-array-at': 'error',
      'e18e/prefer-includes': 'warn'
    },
  },
  {
    plugins: { e18e }
  },
];
```

**Comment by Sysix** [comment]
thank you for looking into this and confirming the global plugins problem :)

**Review by Sysix — APPROVED** [review]

File: src/plugins_rules.ts (hunk 3 above)
Comment (connorshea) [reply src/plugins_rules.ts]: ^ FWIW I did test that just now (with `@eslint-react/dom/` as well) and it worked correctly with no code changes, so we're good!
